apiVersion: v1
kind: Pod
metadata:
  name: myvolumes-pod
spec:
  containers:
  - image: alpine:latest
    imagePullPolicy: Never
    name: myvolumes-container

    command: ['sh', '-c', 'echo Container is Running ; sleep 3600']

    volumeMounts:
    - mountPath: /tmp
      name: example-volume
  volumes:
  - name: example-volume
    emptyDir: {}
